#!/bin/bash

eval messaggio=\$$#
nfiles=$(( $#-1 ))
files=${@:1:$nfiles}

if [ $# -gt 1 ]; then	
	for file in $files; do
		git add $file
	done
	
	git commit -m "$messaggio"
	git push -u origin master

else
	echo
	echo
	echo "	USAGE: 		gitup file1 .. filen \"message\""
fi
